#spring.config.activate.on-profile=dev
#spring.data.mongodb.uri=mongodb://localhost:27017/placement-portal
#logging.level.com.placementportal=DEBUG
#jwt.expiration=2592000000
#app.seed-demo-data=true
